# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
