# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180403_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biddingitem',
            old_name='expireDay',
            new_name='expire_date',
        ),
        migrations.RenameField(
            model_name='biddingrecord',
            old_name='date',
            new_name='bidding_date',
        ),
        migrations.AddField(
            model_name='biddingrecord',
            name='status',
            field=models.CharField(default='waiting', max_length=7),
            preserve_default=False,
        ),
    ]
