# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 03:51
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180419_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='/static/app/images')),
        ),
    ]
