# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180424_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='yabeuser',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yabeuser',
            name='annualIncome',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yabeuser',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
