# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180425_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yabeuser',
            name='annualIncome',
            field=models.CharField(max_length=20),
        ),
    ]
